global using Carter;
global using Identity.API.Data;
global using Identity.API.Extensions;
global using Identity.API.HostedServices;
global using Identity.API.Models;
global using Microsoft.AspNetCore;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Primitives;
global using Microsoft.IdentityModel.Tokens;
global using OpenIddict.Abstractions;
global using OpenIddict.Server.AspNetCore;
global using System.ComponentModel.DataAnnotations;
global using System.Security.Claims;
global using static OpenIddict.Abstractions.OpenIddictConstants;
